# Generated by Django 3.0.2 on 2020-02-06 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OSMData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.IntegerField()),
                ('osm_data', models.TextField()),
                ('anthem_beginning', models.CharField(max_length=256, null=True)),
                ('first_president', models.CharField(max_length=256)),
            ],
        ),
    ]
